import { BOMPart } from "./entity-types.js";

/**
 * @description Represents the output of the initial workbook extraction step.
 * It provides a lightweight summary for LLM analysis and a pointer to the complete data.
 */
export interface WorkbookExtractionResult {
  /**
   * A text-based summary of the workbook, optimized for LLM analysis.
   * Includes sheet names and a simplified grid of cell values.
   */
  workbookSummaryForLlm: string;

  /**
   * The full, structured JSON representation of the workbook.
   * This detailed data is used for deterministic extraction after the LLM has created a plan.
   */
  fullWorkbookData: ExcelWorkbook;
}

/**
 * @description Represents a single cell in an Excel sheet.
 */
export interface ExcelCell {
  address: string;
  value: any;
  formula?: string;
  type: string;
}

/**
 * @description Represents a single row as an array of cells.
 */
export interface ExcelRow extends Array<ExcelCell> {}

/**
 * @description Represents an image found in an Excel sheet.
 */
export interface ExcelImage {
  s3Key: string;
  range: string; // e.g., "A1:B5"
}

/**
 * @description Represents the full structure of a single Excel sheet.
 */
export interface ExcelSheet {
  sheetName: string;
  rowCount: number;
  columnCount: number;
  data: ExcelRow[];
  images: ExcelImage[];
}

/**
 * @description Represents the full JSON structure of an entire Excel workbook.
 */
export interface ExcelWorkbook {
  workbookName: string;
  sheets: ExcelSheet[];
}

/**
 * @description Represents the extraction plan generated by the analysis LLM.
 * This plan guides the deterministic extraction of data from the full workbook structure.
 */
export interface BomExtractionPlan {
  analysis: {
    primarySheetName: string;
    confidence: number;
    reasoning: string;
    projectMetadata: {
      key: string;
      label: string;
      value: any; 
      valueCellAddress: string;
    }[];
    dataTable: {
      sheetName: string;
      headerRow: number;
      dataStartRow: number;
      dataEndRow?: number;
    };
  };
}


/**
 * @description Represents the mapping plan generated by the first LLM call.
 */
export interface MappingPlan {
  [rawHeader: string]: {
    mapsTo: string | null; // Key from MasterFieldList, or null if unmapped
    confidence: number;    // 0.0 to 1.0
  };
}

/**
 * @description Represents the project-level data extracted from the BOM.
 */
export interface ProjectData {
  projectName?: string;
  customerName?: string;
  platformName?: string;
  defaultCurrency?: string;
  defaultWeightUnit?: string;
  [key: string]: any; // Allows for other project-level fields
}

/**
 * @description Represents the final structured output from the structuring stage.
 */
export interface StructuredBOM {
  project: ProjectData;
  parts: BOMPart[];
}

/**
 * @description Represents the output of the validation Lambda.
 */
export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  validatedData: StructuredBOM; // The data with validation errors annotated
  partsCount?: number;
}