import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Crafting the user journey.
 *
 * This sidebar configuration is designed to guide a new user logically
 * through Allma, from understanding the core value proposition to deploying
 * their first workflow and solving common problems.
 */
const sidebars: SidebarsConfig = {
  // We define a single sidebar for all documentation content
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/introduction',
        {
          type: 'category',
          label: 'Key Concepts',
          link: {
            type: 'generated-index',
            title: 'Key Concepts',
            description: 'Learn about the fundamental concepts that power Allma.',
          },
          items: [
            'getting-started/key-concepts/flows-and-steps',
            'getting-started/key-concepts/data-context',
            'getting-started/key-concepts/versioning-publishing',
            'getting-started/key-concepts/architecture-principles',
          ],
        },
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: true,
      items: [
        'how-to-guides/building-your-first-ai-flow',
        'how-to-guides/integrating-with-external-apis',
        'how-to-guides/orchestrating-parallel-workloads',
        'how-to-guides/managing-long-running-processes',
        'how-to-guides/advanced-error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/flow-definition-reference',
        {
          type: 'category',
          label: 'Admin API Reference',
          link: {
            type: 'generated-index',
            title: 'Admin API Reference',
            description: 'A complete guide to the Allma administrative REST API for managing flows, prompts, and monitoring executions.',
          },
          items: [
            'reference/admin-api/flow-management-api',
            'reference/admin-api/flow-control-api',
            'reference/admin-api/execution-monitoring-api',
            'reference/admin-api/prompt-management-api',
          ],
        },
        {
          type: 'category',
          label: 'Step Types Reference',
          link: {
            type: 'generated-index',
            title: 'Step Types Reference',
            description: 'A detailed encyclopedia of every step type available in Allma.',
          },
          // This will automatically create a nested sidebar based on the directory structure
          items: [{type: 'autogenerated', dirName: 'reference/step-types'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: true,
      items: [
        'community/contribution-guide',
        'community/contribution-tutorial',
        'community/maintainer-guide',
        'community/architecture-deep-dive',
      ],
    },
  ],
};

export default sidebars;