name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This is needed to allow changesets to fetch previous tags
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This command will run publishing to npm.
          # It will only be run if the latest commit is a release commit (e.g., "Release v1.2.3").
          publish: npm run release
          # This command will open a PR with version updates.
          # It will be run if there are changeset files, but the latest commit is not a release commit.
          version: npm run version-packages
          commit: "chore: update package versions"
          title: "Upcoming Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}